### ISSUE TITLE
Exception in thread "main" java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by kucingpresto** [mrfaptastic/Glediator3#1]
- Java Version : 1.8.0_261 x64 ( Release date July 14, 2020 )
- Platform : Windows 10 Build 2004.

Hello, i'm encountered some problem caused by java version. Is it possible to backport it into java class version 52, because it's the only version that i can download directly from https://java.com/en/download/ .

Screenshot below, Thanks.

![image](https://user-images.githubusercontent.com/48805732/92341201-2e1d3880-f0e7-11ea-8e36-a646a7ef1d1b.png)

**Comment by mrcodetastic** [comment]
Hi @kucingpresto. I've compiled another verison using Java 12 `Glediator3-binary-JavaSE12.jar`. See if that works.

**Comment by mrcodetastic** [comment]
Out of curiosity, how did you find this repository? I only uploaded this a few days ago :-)

**Comment by mrcodetastic** [comment]
Also, download OpenJDK from here: https://jdk.java.net/14/

**Comment by kucingpresto** [comment]
@mrfaptastic Hi, Thanks for responding, im following your project "ESP32-RGB64x32MatrixPanel-I2S-DMA" and found this repo on one of your example called "Glediator3_TPM2_MatrixPanel".
