### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by dallen98** [mrfaptastic/Glediator3#2]
I am attempting to build a 180x360 matrix using ws2812b eg 180x360=64800 pixels total, I know that the old glediator had quite a low limit on pixels lower in fact than jinx which has a maximum 48000 so do you have any thoughts on increasing this pixel limit on your Glediato3 ? Thanks

**Comment by mrcodetastic** [comment]
There doesn't appear to be a limit on Glediator from what I can see. I did notice that if the resolution is too large the 'live preview' seemed to go black. I've fixed this.

I won't be able to help with performance however. 180x360 is going to need very fast wifi or whatever in order to get the colors out at a decent FPS.

**Comment by dallen98** [comment]
yes i,m struggling for an answer to this, resolume, xlights, glediator using artnet, e131, tmp2.net via serial, ethernet cable, wifi, bluetooth, which route to take ? any suggestions would be much appreciated, i,m looking for around 25fps across my 180x360 thanks

**Comment by dallen98** [comment]
....it doesnt all need to feed from one device, i could have a few esp32 connected on different ports ?

**Comment by mrcodetastic** [comment]
`23*180*360*3bytes per pixel = ~13mbits/sec`

WiFi/Ethernet may be your only option.

Depends on what device you end up using. I think you'd be best using a Raspberry PI to drive the chains of pixels or something or as you say, have multiple ESP 32's. Again, can't really help you here. Trial and error I guess.

**Comment by dallen98** [comment]
so a simple usb serial is a non starter then ? "via. Serial Port - Slow", I read theres a lot of issues with wifi on esp32, rpi only has 2 pwm output pins so i,m going to give ethernet cable a try on esp32 with a enc28j60 module, which protocol do you think would be best ?? thanks

**Comment by mrcodetastic** [comment]
For that size of matrix I would have thought calculating / coding the actual adnimation on the device itself would be the way to go, and not using some tool like Jinx or glediator. Lose the flexibility though.

**Comment by dallen98** [comment]
do you mean creating 180x360 animated gifs to fit the 180x360 matrix exactly and perhaps loading them into the esp32 memory as littlefs spiffs ?

**Comment by mrcodetastic** [comment]
Yes and/or implement the animations, if they're based on an algorithmn (like say the fire animation) in C++ on the ESP32/whatever device you decide to use.

**Comment by dallen98** [comment]
this is advertising on roadside billboards with up to 4x 5 second slots, i,m a novice as youve probably guessed, i would have to look into algorithm in c stuff, what would be the advantage over an animated gif in littlefs ? i will have a raspberry pi connected to the esp32 via usb and this rpi would have arduino ide on it and the rpi would be connected to the internet allowing me to remote desktop into it

**Comment by mrcodetastic** [comment]
For that use-case there would be no advantage, only disadvantages. 

So, animated GIF in littlefs would be easiest option indeed then - total flexibility.

**Comment by dallen98** [comment]
another option again into little fs is a .dat file...
https://github.com/ShaunPrice/FSEQLib

**Comment by vortigont** [comment]
For things like billboard installing a [specialized controller](https://aliexpress.ru/item/32841086964.html) would be much better approach. It has Ethernet/WiFi options along with management software for PC.

**Comment by dallen98** [comment]
yes the specialized controller looks good but I believe they are for hub 75 type panels P10 P6 etc, I want a 16mm pixel pitch that comes with WS2812b / WS2813 / WS2815, the hub75 panels only go up to 10mm pitch correct me if I,m wrong

**Comment by mrcodetastic** [comment]
> 
> 
> this is advertising on roadside billboards with up to 4x 5 second slots, i,m a novice as youve probably guessed, i would have to look into algorithm in c stuff, what would be the advantage over an animated gif in littlefs ? i will have a raspberry pi connected to the esp32 via usb and this rpi would have arduino ide on it and the rpi would be connected to the internet allowing me to remote desktop into it

Why would you need a RPI to remote desktop into it? It would be simpler to write a sketch by the ESP32 to use WiFi to get a .GIF from some webserver, check periodically, and then pump this out to the LEDs. No need for a RPI. 

> the hub75 panels only go up to 10mm pitch correct me if I,m wrong

I think that's right.

**Comment by dallen98** [comment]
Because I also want to regularly view the advertising hoarding on camera to check its working and with the arduino ide loaded on the remote rpi i can update/change the code.
What would be cool is an optimised tpm-net sketch like you have for hub 75 panels but for neomatrix panels using fastled off esp32.
Is there any plans to have multiple input devices with seperate ip adresses like in jinx ?

**Comment by vortigont** [comment]
@dallen98 you might want to look into [this](https://github.com/hzeller/flaschen-taschen) project.
It could drive RGB panels from RPi either via network stream or from a local data/files. RPi has more resources on-board to crunch things like gifs/long animation.

**Comment by dallen98** [comment]
The billboard needs to be physically large NB 6mx3m (20feetx10feet) using a 16mm pitch led is 180 pixels high x 360 pixels wide, 180x360=64800 leds total, my understanding correct me if i,m wrong is that the ws2812b can only come from pwm pins only of which there are only 2 on the pi, this said i see that... "This adapter to the Raspberry Pi can support up to 16 SPI LED strips (e.g. WS2801 or APA102) at once." [https://github.com/hzeller/flaschen-taschen/tree/master/hardware](url) sounds promising, 16mm pitch is what i,m locked into right now through reasons of economy and 16mm pitch doesnt come in the rgb panels but does come in ws2801, apa102 and ws2812b

**Comment by vortigont** [comment]
quite a big board :) might be difficult to clock such a long strips of LEDs. ws2812b is no-go, those ones are clockless and you'll probably face timing issues with it. APA102 might be an option, the board mentioned above uses 16 data pins + clock and a bunch of bus drivers to control 16 parallel LED strips.

**Comment by dallen98** [comment]
how many leds could i get on each of the 16 rpi pins ?
 I can (in theory) drive 900 ws2812b leds off of 80 virtual pins out of esp32 but still working on this maybe using spiffs.
Ive also seen arduino code being run on the rpi which could be a thought.

**Comment by dallen98** [comment]
what is the maximum number of ws2812b leds that can be driven on this glediator3 tpm-net at 25fps ??

**Comment by mrcodetastic** [comment]
That's for you to determine through experimentation. This is git repo is simply Glediator decompiled + a fix to the Serial Port connectivity.  I think it was originally designed only for small (64x64) displays. It's too slow for anything serious I think.
